server:
  port: 0
spring:
  application:
    name: school-service
  datasource:
    url: jdbc:mariadb://localhost:3306/hr1
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  zipkin:
    base-url: http://localhost:9411
 
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
logging:
  file:
    name: coupon-service.log
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true  
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}